language: java

jdk:
- oraclejdk8
# `openjdk8` not available; Java 7 not supported because of lambda expressions

install:
- git clone --recursive https://github.com/krichter722/maven-parent && cd maven-parent && mvn install && cd ..

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version
# add --update-snapshots if snapshots are used
- mvn test verify --batch-mode
